### ISSUE TITLE
*.by_calendar_month('May') looks wrong 

### ISSUE THREAD

**Issue by mzaragoza** [radar/by_star#53]
I just installed the gem and was playing with it but I just did 

Consumers.by_calendar_month('May').to_sql and I got back 
SELECT \"consumers\".* FROM \"consumers\" WHERE \"consumers\".\"account_id\" = 1 AND (consumers.created_at >= '2015-04-27 00:00:00.000000' AND consumers.created_at <= '2015-05-31 23:59:59.999999')" 

End date is perfect but start daye seems like its to far back

**Comment by radar** [comment]
Yeah that definitely doesn't look right. Can you reproduce this in a brand new app as well?

**Comment by mzaragoza** [comment]
It looks that some one fixed it.

**Comment by johnnyshields** [comment]
This isn't an issue. There is a difference between "by_month" and "by_calendar_month". The latter includes days which appear on a calendar. (In your case your beginning of week is Monday)

![image](https://cloud.githubusercontent.com/assets/27655/7466400/14f5c278-f31d-11e4-9895-cd223709db3d.png)

**Comment by mzaragoza** [comment]
Thanks for explaining this to me.  I had just selected the wrong method. 
and I appreciate you getting back to me. Keep up the good work
