### ISSUE TITLE
More intelligent between_times

### ISSUE THREAD

**Issue by spdawson** [radar/by_star#60]
Where either or both of the `start` and `finish` timestamps could be absent, it is often necessary to have logic such as the following.

```ruby
relation = run_some_query
relation = if start.present? && finish.present?
  relation.between_times(start, finish)
elsif start.present?
  relation.after(start)
elsif finish.present?
  relation.before(finish)
else
  relation
end
```

I'm wondering whether either of the following would be acceptable.
1. Add a new method to encapsulate this logic; for example `between_optional_times`
2. Add an option to the existing `between_times`, to switch the behaviour into this "optional timestamps" mode of operation; for example `between_times(start, finish, optional: true)`

I'm happy to code this up if there are no objections to the addition of this feature.

**Comment by johnnyshields** [comment]
@spdawson I've been working on exactly this issue

I have code which isn't committed yet. Will add in 2-3 weeks (next in my queue after current task)

**Comment by johnnyshields** [comment]
Code work-in-progress is here FYI:
https://github.com/johnnyshields/by_star/commit/1e7c1b4e69425258d368f308d3fc0cb3f45491d1

**Comment by johnnyshields** [comment]
Checkout the readme comment and see if it makes sense.

**Comment by johnnyshields** [comment]
PR #63 fixes this.

**Comment by spdawson** [comment]
I may be reading the changes in PR #63 incorrectly, but I don't see that it really addresses the issue described here. If I were to call `between_times(nil,Time.zone.now)` it would not give the same result as calling `before(Time.zone.now)`. Right?

**Comment by johnnyshields** [comment]
@spdawson it does give the same result as `before(Time.zone.now)`

**Comment by johnnyshields** [comment]
The relevant code is below. Try it for yourself.

```ruby
      scope = if !end_time
                by_star_after_query(scope, start_field, start_time)
              elsif !start_time
                by_star_before_query(scope, start_field, end_time)
              elsif start_field == end_field
                by_star_point_query(scope, start_field, start_time, end_time)
              elsif options[:strict]
                by_star_span_strict_query(scope, start_field, end_field, start_time, end_time)
              else
                by_star_span_overlap_query(scope, start_field, end_field, start_time, end_time, options)
              end
```

**Comment by spdawson** [comment]
My bad: PR #63 does of course deal with this issue; I was reading PR #61, for some reason.

Thanks for this --- looks just the ticket.
