### ISSUE TITLE
Release of v2.2.2 or v3.0.0

### ISSUE THREAD

**Issue by existent-ltd** [radar/by_star#67]
Are there any plans to release v2.2.2 or v3.0.0 in the near future?

**Comment by johnnyshields** [comment]
yes, soon. I'll add this to my queue.

**Comment by johnnyshields** [comment]
actually the only thing I'm waiting on is to fix the failing specs for #66. If you want to take a look and help you're welcome to.

**Comment by radar** [comment]
Hi @ghost. Sorry for the delay. v3.0.0 has been released last week.
