### ISSUE TITLE
Next_week does not work 

### ISSUE THREAD

**Issue by saroar** [radar/by_star#68]
Would you like to check where i make mistake 
here is my code 

Past week
http://prntscr.com/ciortp
where my past week task 

Current Week i don't by this 
Task.between_times(Date.current.beginning_of_week, Date.current.end_of_week)
also in current week i cant see my future task list too :(
http://prntscr.com/cips6f

but when i try next_week it does not work 
http://prntscr.com/cipsht

here is my table info for task 

# Table name: tasks
#
#  id            :integer          not null, primary key
#  title         :string
#  description   :text
#  status        :integer          default("defualt")
#  reviewer_id   :integer
#  project_id    :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  position      :integer
#  working_hours :integer          default(0)
#  deadline      :datetime
#  start_day     :datetime

**Comment by johnnyshields** [comment]
Please raise a PR with a failing test case if you would like help with an issue.
