### ISSUE TITLE
Remove miliseconds on sql generated 

### ISSUE THREAD

**Issue by mada41** [radar/by_star#69]
hi @radar , Thanks for the great gem.
I use it on production and now since the data is large, i need improve a bit.
The example generated date on sql query is `2016-09-30 16:59:59.999999`. There is any option for remove the seconds and timestamp? 

Thanks.

**Comment by johnnyshields** [comment]
@mada41 why would this make a difference in performance?

**Comment by mada41** [comment]
thanks for replay @johnnyshields .
Nevermind,, something wrong with my index. Closing now
