### ISSUE TITLE
Any way to simulate by_days

### ISSUE THREAD

**Issue by wbotelhos** [radar/by_star#71]
So, I have a installment with due date at '2016-01-10', and I want to notify the user x days before this date. I case I want choose how many days that can be 0 days (the same day of due date) and 3 days before. Like so:

`first notification -> '2016-01-07'`
`second notification -> '2016-01-10'`
`due_date -> '2016-01-10'`

The method could be like that:

`.by_dates([Time.zone.local(2016, 1, 7), Time.zone.local(2016, 1, 10)])`

Or something crazy like the following:

`.by_left(base: Time.current, days: [0, 3], field: :due_date)`

Maybe a `IN` with `utc.to_day` or something like that. Is it possible?

Thank you and congrats by the great gem. (:

**Comment by radar** [comment]
A bit late, but I think you can do this using the `or` query:

```ruby
Project.by_day(Time.now).or(Project.by_day(1.day.ago))
```
