### ISSUE TITLE
Between the same DateTime behavior

### ISSUE THREAD

**Issue by beitaz** [radar/by_star#72]
```
user.orders.between_times(Time.zone.now, Time.zone.now)
```
Result is empty,  it shouldn't like this, i guess. What happened? 
```
SELECT * FROM `orders` WHERE created_at BETWEEN "now" AND "now";
```

**Comment by radar** [comment]
https://en.m.wikipedia.org/wiki/Zeno's_paradoxes#Arrow_paradox

We don't validate the times people use. It's up to you to do that validation.

Nothing happens at all between the same time. The arrow, or in this case, database, is motionless.

**Comment by beitaz** [comment]
Thanks! But the situation is as follows:
```
SELECT `orders`.* FROM `orders` WHERE (orders.created_at >= '2016-11-18 06:01:32' AND orders.created_at <= '2016-11-18 06:01:32') ORDER BY `orders`.`id` DESC
```
What i want is this(Note this `=`):
```
SELECT `orders`.* FROM `orders` WHERE (orders.created_at > '2016-11-18 06:01:32' AND orders.created_at < '2016-11-18 06:01:32') ORDER BY `orders`.`id` DESC
```

**Comment by radar** [comment]
But you're specifying the same time. There isn't going to be any records regardless.

**Comment by johnnyshields** [comment]
I think this is a reasonable request, to return records which start exactly at that time.

**Comment by johnnyshields** [comment]
Actually I added support for this on this PR: https://github.com/radar/by_star/pull/66 via the `at_time` method. Haven't merged yet do to failing specs, I need to do so.
