### ISSUE TITLE
Support by_hour, by_minute, and other times

### ISSUE THREAD

**Issue by victorhazbun** [radar/by_star#73]
Currently there is no way to query for hour, minute and so on. The only scopes available are between times. Do you plan to implement those in the future? Do you accept pull requests?

I have made this in order to accomplish my goals tested in PostgreSQL (you may want to use this as well):

    scope :by_created_at_hour, -> (hour) { where("date_part('hour', created_at) = ?", hour) }

    scope :by_created_at_minute, -> (minute) {where("date_part('minute', created_at) = ?", minute) }

**Comment by radar** [comment]
I can't speak about what future plans are (since I personally no longer maintain this, but @johnnyshields does)... but I can say that pull requests are indeed very welcome!

**Comment by johnnyshields** [comment]
If you'd like to raise a PR for it I'd be glad to merge.
