### ISSUE TITLE
by_star_field with :scope doesn't work properly for class methods (ex. newest)

### ISSUE THREAD

**Issue by ndac-todoroki** [radar/by_star#75]
I have a model like this:

```ruby
class TodoList < ActiveRecord::Base
  ## Associations
  belongs_to :chat_room

  ## Validations
  validates_presence_of :chat_room_id
  validates_presence_of :date
  validates_associated :chat_room
  validates_uniqueness_of :chat_room_id, {scope: :date}

  ## ByStar Settings
  by_star_field :date
  by_star_field scope: ->(record) { where(chat_room: record.chat_room) }
  ...
```

here at the last row, I want ByStar to look separately between `TodoList`s of different `ChatRoom`s.
This does work for instance methods like `next` `previous`

```ruby
TodoList.last.previous
#   TodoList Load (0.9ms)  SELECT  `todo_lists`.* FROM `todo_lists`  ORDER BY `todo_lists`.`id` DESC LIMIT 1
#   ChatRoom Load (0.9ms)  SELECT  `chat_rooms`.* FROM `chat_rooms` WHERE `chat_rooms`.`id` = 1 LIMIT 1
#   TodoList Load (0.7ms)  SELECT  `todo_lists`.* FROM `todo_lists` WHERE `todo_lists`.`chat_room_id` = 1 AND (date < '2017-05-18')  ORDER BY date DESC LIMIT 1
# => #<TodoList:0x0055845f838b58
#  id: 1,
#  date: Wed, 17 May 2017,
#  comment: "Test",
#  chat_room_id: 1,
#  created_at: Wed, 17 May 2017 12:45:42 UTC +00:00,
#  updated_at: Wed, 17 May 2017 12:45:42 UTC +00:00>
```

but not for class methods:

```ruby
TodoList.newest
# RuntimeError: ByStar :scope does not accept arguments
```

as for https://github.com/radar/by_star/issues/39, I thought class methods and instance methods should differentiate scopes. I think this is not working well.

**Comment by johnnyshields** [comment]
Did you try:

```
  ## ByStar Settings
  by_star_field :date, scope: ->(record) { where(chat_room: record.chat_room) }
```

**Comment by ndac-todoroki** [comment]
@johnnyshields thanks, tried that, but still raises error for `TodoList.newest` nor `ChatRoom.first.todo_lists.newest`
Only `:date` should be applied to `newest`, but I think `where(chat_room: record.chat_room)` is applied too

**Comment by johnnyshields** [comment]
@ndac-todoroki what error is raised?

**Comment by ndac-todoroki** [comment]
@johnnyshields
same as above,
```
RuntimeError: ByStar :scope does not accept arguments
```

**Comment by radar** [comment]
I am not sure why `:scope` is even required in this library. I am removing this feature in 422c06e, and it will be gone in the 3.1 release.

Consider using `ChatRoom.first.todo_list.newest` instead. From what I can tell, this will do the query that you want.
