### ISSUE TITLE
How to query between two fields?

### ISSUE THREAD

**Issue by brunohkbx** [radar/by_star#79]
I need to query a table using the fields start_at and end_at.
Is it possible to do that using the gem?

`.where("start_at >= ? and end_at <= ?", start_date, end_date)`

**Comment by weiWang95** [comment]
You can try`.after(start_at, field: :start_at).before(end_at, field: :end_at)`

**Comment by radar** [comment]
Yes, `after` + `before` will work fine for this case. Thank you @weiWang95 :)
