### ISSUE TITLE
Best practice for frontend

### ISSUE THREAD

**Issue by schristm** [radar/by_star#81]
Hi Ryan,

Very nice gem! Do you have a recommended way of connecting these finders to the frontend? Right now I have a dropdown menu that links to the current page with a `range` parameter, referencing scopes named `this_month`, `last_month`,`last_7_days`, etc.

It would be nice if I could just call something like `People.by_star(params[:range])`. As of right now, it seems I'd need to still keep my own scopes, but instead using my own where conditions, I'd call a scope provided by ByStar. Not as DRY as I would like, but it works.

Do you have any other recommendations?

**Comment by radar** [comment]
Thanks!

It sounds like you could have some custom logic in your Rails controllers to split out the range parameter into something by_star could work with. That’s what I would do at least.
